---
- hosts: mywebservers
  become: yes
  tasks:
  - name: install java on ubuntu ansible nodes
    apt:
      name: "{{mywebpackforubuntu}}"
      state: present 
    when: ansible_os_family =="Debian"

  - name: install java on redhat ansible nodes
    yum:
      name: "{{mywebpackforredhat}}"
      state: present 
    when: ansible_os_family =="RedHat"