---
- hosts: mywebservers
  become: yes
  taks:
  - name: install java on ubuntu ansible nodes
    apt:
     name: "{{openjdk-8-jre}}"
     state: present
    when: ansible_os_family =="Debian"

  - name: install java on redhat ansible nodes
    yum:
      name: "{{mywebpackforredhat}}"
      state: present
    when: ansible_os_family =="RedHat"