---
- hosts: mywebservers
  gathering_facts: yes
  become: yes
  - name: i want to install java on ubuntu nodes
    apt: 
     name: "{{openjdk-8-jre}}"
     state: present
    when: ansible_os_family =="Debian"

  - name: i want to install java on RedHat nodes
    yum:
     name: "{{java-1.8.0-o}}"
     state: present
    when: ansible_os_family =="RedHat" 
