---
- hosts: 172.31.1.92
  become: yes
  vars:
    myvar1: git
    myvar2: tree
    myvar3: wget
  tasks:
  - name: i want to display myvar1
    debug:
      msg: "[{myvar1}}"

  - name: i want to install git
    apt:
     name: "{{myvar1}}"
    loop:
     - "{{myvar1}}"
     - "{{myvar2}}"
     - "{{myvar3}}"