---
- hosts: 172.31.9.190
  become: yes
  tasks:
  - name: install git
    apt:
       name: git
       state: present
    tags: mygit

  - name: install tree
    apt:
       name: tree
       state: present
    tags: mytree
    ignore_errors: yes

  - name: installllll wget
    apt:
      name: wget
      state: present 
    tags: mywget
